# Generated by Django 3.0.6 on 2020-05-24 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200523_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='avater.jpg', upload_to='media'),
        ),
    ]
