# Generated by Django 3.0.6 on 2020-05-24 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200524_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(default='avatar.jpg', upload_to='media'),
        ),
    ]
